### ISSUE TITLE
Send Diagnostics Data

### ISSUE THREAD

**Issue by tnez** [pebble-io/client-browser#25]
### Context

As a way to monitor real-world performance of our Pebble service, we want to send real-time diagnostics data that indicates how long it takes for the client to first initialize (this means when initializing from service rather than cache).

This will give us appropriate feedback to help us monitor and improve our service.

As part of this, we will want to identify what context data we want to send along with these events. Most likely this context data will be common to all messages that we send from the browser.

### Tasks

- [x] identify the desired shape of context data (@joshuaswearingen has been working towards this on his end)
- [x] implement a utility to provide context data and enforce some type-safety around it
- [x] re-implement general message sending
- [x] identify and wire-up a destination for these messages

---
**Implemented:** #27, #28
**Released:** #29
